### PR TITLE
Fix issue with desktops using the --use-display flag being shifted 2.25 px down

### PR DESCRIPTION
**Pull request by CorbinWunderlich**
Had to create this new one because github wouldn't let me reopen #337 . Anyway, this solution is a little bit hardcoded, but it should be fine (most likely).

### CODE REVIEW

**Comment by totaam** [comment]
How did you come up with 2.25? by the eye?
Isn't this likely to change based on hidpi, platform, etc?

What is the difference in resolution between a new session and a `--use-display` one?

I would prefer fixing the underlying bug (whatever that may be) rather than hard-coding values I don't understand.

**Comment by CorbinWunderlich** [comment]
Yes, this is valid. I will try to fix the bug normally.

**Comment by CorbinWunderlich** [comment]
> How did you come up with 2.25? by the eye? Isn't this likely to change based on hidpi, platform, etc?
> 
> What is the difference in resolution between a new session and a `--use-display` one?
> 
> I would prefer fixing the underlying bug (whatever that may be) rather than hard-coding values I don't understand.

This is probably better.

**Comment by CorbinWunderlich** [comment]
Oh, I left some stuff in. One second, I will get rid of those.

**Comment by CorbinWunderlich** [comment]
There, that should do it.

**Comment by CorbinWunderlich** [comment]
Just added some changes that would edit some icons (delete unused ones and update the 4 year old Material Icons). Note that they have been updated to 2 year old Material Icons, as the ttfs that they provide are deprecated

**Comment by totaam** [comment]
Can you keep the icon changes separate?
Also, I don't see what replaces the speaker and clipboard icons.

**Comment by CorbinWunderlich** [comment]
I can keep them separate. The speaker and clipboard icons are not mentioned anywhere and are not used

**Comment by totaam** [comment]
Ah, silly me! 
Makes sense.

**Pull request merged**
