### PR TITLE
Add NodeJS-less formatting script

### PR DESCRIPTION
**Pull request by CorbinWunderlich**
[JS-beautify](https://github.com/beautifier/js-beautify) is a non-intrusive formatting solution, that is fairly configurable and has reasonable formatting choices (though it is preference). This PR deletes NodeJS, and adds a `format.sh` script for formatting the files and installing nix in one. Solves the complaints about formatting in #306. The `shell.nix` fetches the newest stable version of nixpkgs at the time (24.05, though 24.11 is coming soon), to add enough consistency and version pinning since I believe that a flake is too complex for such a simple task.

_This PR does **not** format the files with this new formatter, but instead just adds the formatter._

### CODE REVIEW

**Comment by totaam** [comment]
`lib` should be left untouched as these files are updated in-place from their respective upstreams.

**Comment by CorbinWunderlich** [comment]
> `lib` should be left untouched as these files are updated in-place from their respective upstreams.

Done

**Comment by CorbinWunderlich** [comment]
@totaam Wow, that was fast. If you want, you can run the formatter and commit the changes.

**Comment by totaam** [comment]
Whoohoo - it's finally gone.

@sbradnick this will be music to your ears.

**Comment by CorbinWunderlich** [comment]
As another thing, if you try to commit, you might get a husky error because the git hooks still exist (unfortunately). Delete the .git/hooks directory, then run `git init` to reinitialize the default git hooks

**Comment by CorbinWunderlich** [comment]
> > Whoohoo - it's finally gone.
> > @sbradnick this will be music to your ears.
> 
> I realized I forgot to delete the .husky directory. I could do that or you could quickly do that. Very minor, sorry for my mistake

#333

**Pull request merged**
