### PR TITLE
Unify eslint & prettier and merge configurations

### PR DESCRIPTION
**Pull request by andersevenrud**
This pull-request unifies ESLint and Prettier so that it's possible to use `eslint` CLI for all checks and formatting.

Also places all of the configurations inside `package.json` to reduce noise.

### CODE REVIEW

**Comment by andersevenrud** [comment]
Sorry if steps on your work in #184 @JanCVanB :sweat_smile:

**Comment by JanCVanB** [comment]
Not at all.

**Review by JanCVanB — APPROVED** [review]
Assuming that `npm run format` has the exact same result, this looks simpler to me!

**Comment by andersevenrud** [comment]
> Assuming that npm run format has the exact same result, this looks simpler to me!

Yup. ESLint now invokes Prettier and interprets the messages as linter errors, and the `--fix` arguments invokes a Prettier write :)

**Pull request merged**
