### PR TITLE
noVNC-style vertical menu

### PR DESCRIPTION
**Pull request by CorbinWunderlich**
TODO:
- [x] Make it an option and fix the hardcoding
- [x] Make it less opinionated (right now it just looks like how I want it...)
- [x] Button to make the menu pop out (optional)
- [x] Fix formatting (I use 4 indents and Xpra uses 2)

I could use some suggestions for a proper name for it other than "noVNC style menu".

### CODE REVIEW

**Comment by CorbinWunderlich** [comment]
Don't worry about the commit names, I will go back and squash when I'm done

**Comment by CorbinWunderlich** [comment]
What would be the best way to add this other type of menu? Should I hack together something in HTML or just give up and make a different element for this style of menu? I don't know

**Comment by CorbinWunderlich** [comment]
I'm sorry @totaam , but eslint is erroring out for me. If you could checkout the branch and just run the formatting for me, that would be of great help. Other than that, I think I finished all the implementations of everything, just check over it. Thanks!

**Comment by totaam** [comment]
Let's completely ignore whatever mess `eslint`was suggesting. 
In fact, can you undo the formatting changes from your commit? 
For a start, it will make it much easier to review.

**Comment by CorbinWunderlich** [comment]
> Let's completely ignore whatever mess `eslint` was (going to be) suggesting. In fact, can you undo the formatting changes from your commit? For a start, it will make it much easier to review.

I tried to do as best of a job I could, but it still does have significant diffs from the old commits (probably just due to moved lines from the formatter I used). I could fix it further if you want

**Comment by totaam** [comment]
> I could fix it further if you want

Yes, please. 
Codestyle changes shouldn't be mixed with real useful changes.

**Comment by CorbinWunderlich** [comment]
Should be all good now @totaam

**Comment by CorbinWunderlich** [comment]
On a side note, it seems that prettier is the formatter xpra-html5 uses. Prettier should either be removed or run once in a while, since it appears it hasn't been run for a long time. Not a huge issue though.

**Comment by totaam** [comment]
Thanks!

**Comment by totaam** [comment]
> Prettier should either be removed

Yes, I would love to do that - I've had to undo some of the obnoxious changes it made.

The question is, where?

**Comment by CorbinWunderlich** [comment]
> > Prettier should either be removed
> 
> Yes, I would love to do that - I've had to undo some of the obnoxious changes it made.
> 
> The question is, where?

I'm pretty sure it is due to the git hooks on the husky npm package. It seems that the npm build system really doesn't serve any purpose, so I am pretty sure the entire thing can be removed. If that is not doable, just remove the hook that runs prettier. I have no experience with nodejs, but it should probably be in package.json

**Comment by totaam** [comment]
> so I am pretty sure the entire thing can be removed

I would love to do that! It only causes problems: https://github.com/Xpra-org/xpra-html5/issues/306#issuecomment-2113943637
But how?

**Comment by CorbinWunderlich** [comment]
> > so I am pretty sure the entire thing can be removed
> 
> I would love to do that! It only causes problems: [#306 (comment)](https://github.com/Xpra-org/xpra-html5/issues/306#issuecomment-2113943637) But how?

We should probably move this to a discussion or issue instead of a closed PR, but when I said to "remove the whole thing," I meant that NodeJS in it's entirety could probably be removed. I don't know if there is something that people actually use inside of it, but afaik it only makes things harder.

**Comment by CorbinWunderlich** [comment]
I have found a pretty configurable and non-intrusive html and JS formatter, however, like all formatters, it is a compromise. A weak and lenient formatter like this one does not make a line break after a few tokens, but it cannot enforce a strict code style. An intrusive formatter like prettier would enforce a strict code style, but prettier is very unconfigurable and has a really annoying tendency to create newlines when they are not necessary.

I think I agree with you when you said to remove everything node related. This project is not in need of a system like that

**Comment by totaam** [comment]
> but it cannot enforce a strict code style

I think that's a positive thing!

> prettier is very unconfigurable and has a really annoying tendency to create newlines when they are not necessary

Hear hear!
9e30e97b4efcdde481166043679d962fa76484ab, 020e33adeb629a4b244b6d84a574da8a0a1e61cb, 4de32bdb4933d9ba659da1dd1de6d456b6e33fc1, 76a406d55b040b72014637d0306b9b5b9bc15453, bf75a50dd994bbbe6b00e946d0014209b551ccbd, f071b44a6111cb60b4a98f94a5844fa1fad3c5e7, cffed14e08fb296cdd071497ffd399ce987e5719, 2d2a19a5dba1b67b6635cd168bdacca6f10bbba9

**Comment by CorbinWunderlich** [comment]
> > but it cannot enforce a strict code style
> 
> I think that's a positive thing!
> 
> > prettier is very unconfigurable and has a really annoying tendency to create newlines when they are not necessary
> 
> Hear hear! [9e30e97](https://github.com/Xpra-org/xpra-html5/commit/9e30e97b4efcdde481166043679d962fa76484ab), [020e33a](https://github.com/Xpra-org/xpra-html5/commit/020e33adeb629a4b244b6d84a574da8a0a1e61cb), [4de32bd](https://github.com/Xpra-org/xpra-html5/commit/4de32bdb4933d9ba659da1dd1de6d456b6e33fc1), [76a406d](https://github.com/Xpra-org/xpra-html5/commit/76a406d55b040b72014637d0306b9b5b9bc15453), [bf75a50](https://github.com/Xpra-org/xpra-html5/commit/bf75a50dd994bbbe6b00e946d0014209b551ccbd), [f071b44](https://github.com/Xpra-org/xpra-html5/commit/f071b44a6111cb60b4a98f94a5844fa1fad3c5e7), [cffed14](https://github.com/Xpra-org/xpra-html5/commit/cffed14e08fb296cdd071497ffd399ce987e5719), [2d2a19a](https://github.com/Xpra-org/xpra-html5/commit/2d2a19a5dba1b67b6635cd168bdacca6f10bbba9)

Alright, the one I was using was https://github.com/beautifier/js-beautify. We could still use node (not a huge fan, a lot of boilerplate and unnecessary files for nothing) or we could use nix or something. 

For nix, a shell.nix would look like
```nix
let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-24.05";
  pkgs = import nixpkgs { };
in
pkgs.mkShell {
  nativeBuildInputs = with pkgs; [ nodePackages.js-beautify ];
}
```

However, nix is kind of annoying to install on windows (less annoying on anything else, but still inconvenient if you aren't using nixOS like I am). So maybe node is better in that regard? I don't know, I don't use node

**Comment by totaam** [comment]
I very much dislike the cost of running `nodejs` and the complexity involved.
I don't use MS Windows as a development platform, so that doesn't matter.
I would prefer anything that can be installed from the default Fedora repos - not sure what they have.
Alternatively, anything that doesn't bring a gazillion dependencies with it.
Something like `ruff` for Python.

**Comment by CorbinWunderlich** [comment]
> I very much dislike the cost of running `nodejs` and the complexity involved. I don't use MS Windows as a development platform, so that doesn't matter. I would prefer anything that can be installed from the default Fedora repos - not sure what they have. Alternatively, anything that doesn't bring a gazillion dependencies with it. Something like `ruff` for Python.

Right. Fedora's repos weridly package a perl rewrite of js-beautifier, but not the actual thing. I don't know if the perl version has a cli, or just a module. Nix [can be installed on fedora](https://gist.github.com/matthewpi/08c3d652e7879e4c4c30bead7021ff73). If I am not wrong, it has a few deps and is roughly 500mb. 

I think the right course of action is to start with removing node, and if needed, another formatter can be added, but only if it is needed.

**Comment by CorbinWunderlich** [comment]
@totaam If you would like a formatter, I believe I have come to a fairly satisfactory solution. 

- All of NodeJS is deleted
- Instead of adding NodeJS in shell.nix, js-beautify is added instead
- .jsbeautifyrc is created to declare formatter options
- formatter is (I believe) relatively non-intrusive and does not make any draconian changes, but instead smooths out inconsistencies.

I have gotten it working, so I could make a draft pr if you want. I would probably need to edit the README to add in that to contribute, run `nix-shell`, and inside the shell, run `js-beautify -r [any files you edited]`. I could also add to use the [determinate nix installer](https://github.com/DeterminateSystems/nix-installer) to easily install nix on anything with one command

**Comment by CorbinWunderlich** [comment]
I could also add a `format.sh` shell script

**Comment by totaam** [comment]
> All of NodeJS is deleted

I'm sold.

**Comment by CorbinWunderlich** [comment]
> > All of NodeJS is deleted
> 
> I'm sold.

#332

**Pull request merged**
